language: php
    - 7.3
    - 7.4
    - 8.0
    - nightly

script:
    - composer self-update
    - composer install --no-interaction --no-scripts
    - vendor/bin/phpunit --coverage-clover coverage/coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
